async function generatePlan() {
const API_URL =
    location.hostname === "127.0.0.1" ||
    location.hostname === "localhost"
        ? "http://127.0.0.1:8000"
        : "";
const exam =
    document.getElementById("exam").value;

const hours =
    parseInt(
        document.getElementById("hours").value
    );

const subjects = [];

for (let i = 1; i <= subjectCount; i++) {

    const subjectInput =
        document.getElementById(`subject${i}`);

    if (!subjectInput) continue;

    const name = subjectInput.value.trim();

    if (name !== "") {
        subjects.push({
            name,
            exam_date:
                document.getElementById(`date${i}`).value,
            priority:
                document.getElementById(`priority${i}`).value,
            preparation:
                document.getElementById(`prep${i}`).value
        });
    }
}
if (subjects.length === 0) {
    alert("Please enter at least one subject.");
    return;
}
if (!exam || !hours) {

    alert(
        "Please fill Exam Name and Hours Per Day."
    );

    return;
}

try {

    document.getElementById("result").innerHTML = `

    <div class="loading-card">

        <div class="spinner"></div>

        <p>
            Generating Study Plan...
        </p>

    </div>

`;

    const response = await fetch(
    `${API_URL}/generate-plan`, 
        {
            method: "POST",

            headers: {
                "Content-Type":
                    "application/json"
            },

            body: JSON.stringify({
                exam,
                subjects,
                hours_per_day: hours
            })
        }
    );

    if (!response.ok) {

        throw new Error(
            `Server Error: ${response.status}`
        );
    }

    const data =
        await response.json();

    let html = `

        <h2>
            📚 Personalized Study Plan
        </h2>

        <div class="progress-container">

            <div class="progress-text">
                📈 Progress: 0% Completed
            </div>

            <div class="progress-bar">

                <div
                    class="progress-fill"
                    id="progressFill">
                </div>

            </div>

        </div>

    `;

    data.study_plan.forEach((day) => {

        html += `

            <div class="day-card">

                <h3 class="day-title">
                    📅 ${day.date}
                </h3>

        `;

        day.tasks.forEach((task) => {

            html += `

                <div class="plan-card">

                    <div class="plan-left">

                        <input
                            type="checkbox"
                            class="task-checkbox">

                        <span class="task-text">
                            ${task}
                        </span>

                    </div>

                    <div class="task-badge">
                        Study
                    </div>

                </div>

            `;

        });

        html += `
            </div>
        `;

    });

    html += `

        <h2>
            📚 Subject Workspaces
        </h2>

        <div class="workspace-section">

    `;

    subjects.forEach((subject) => {

        html += `

            <button
                class="workspace-btn"
                onclick="openWorkspace('${subject.name}')">

                📚 ${subject.name} Workspace

            </button>

        `;

    });

    html += `

        </div>

        <div class="quote">

            "Success is the sum of small efforts repeated every day."

        </div>

        <div class="footer">

            🚀 Generated by StudySprint AI

        </div>

    `;

    document.getElementById("result")
        .innerHTML = html;

    updateProgress();

    loadProgress();

} catch (error) {

    document.getElementById("result")
        .innerHTML = `

        <div class="plan-card">

            ❌ ${error.message}

        </div>

    `;

}

}

function updateProgress() {

const checkboxes =
    document.querySelectorAll(
        ".task-checkbox"
    );

checkboxes.forEach((checkbox) => {

    checkbox.addEventListener(
        "change",
        () => {

            const badge =
                checkbox
                    .closest(".plan-card")
                    .querySelector(
                        ".task-badge"
                    );

            if (checkbox.checked) {

                badge.innerHTML =
                    "Completed";

                badge.classList.add(
                    "completed-badge"
                );

            } else {

                badge.innerHTML =
                    "Study";

                badge.classList.remove(
                    "completed-badge"
                );

            }

            const total =
                document.querySelectorAll(
                    ".task-checkbox"
                ).length;

            const completed =
                document.querySelectorAll(
                    ".task-checkbox:checked"
                ).length;

            const percent =
                total === 0
                ? 0
                : Math.round(
                    (completed / total) * 100
                );

            document.querySelector(
                ".progress-text"
            ).innerHTML =
                `📈 Progress: ${percent}% Completed`;

            document.getElementById(
                "progressFill"
            ).style.width =
                percent + "%";

            saveProgress();

        }
    );

});

}

function saveProgress() {

    const checkboxes =
        document.querySelectorAll(".task-checkbox");

    const progressData = [];

    checkboxes.forEach((checkbox) => {
        progressData.push(checkbox.checked);
    });

    const studyKey =
        "studyProgress_" +
        document.getElementById("exam").value;

    localStorage.setItem(
        studyKey,
        JSON.stringify(progressData)
    );
}

function loadProgress() {

    const studyKey =
        "studyProgress_" +
        document.getElementById("exam").value;

    const savedData =
        localStorage.getItem(studyKey);

    if (!savedData) {
        return;
    }

    const progressData =
        JSON.parse(savedData);

    const checkboxes =
        document.querySelectorAll(".task-checkbox");

    checkboxes.forEach(
        (checkbox, index) => {

            checkbox.checked =
                progressData[index] || false;

        }
    );

    document
        .querySelectorAll(".task-checkbox")
        .forEach((cb) => {

            cb.dispatchEvent(
                new Event("change")
            );

        });
}
let currentSubject = "";

function openWorkspace(subject) {

currentSubject = subject;

document.getElementById(
    "workspaceTitle"
).innerHTML =
    `📚 ${subject} Workspace`;

const savedData =
    JSON.parse(
        localStorage.getItem(
            `workspace_${subject}`
        )
    ) || {};

document.getElementById(
    "workspaceNotes"
).value =
    savedData.notes || "";

document.getElementById(
    "workspaceYoutube"
).value =
    savedData.youtube || "";

document.getElementById(
    "workspacePdf"
).value =
    savedData.pdf || "";

document.getElementById(
    "workspaceBook"
).value =
    savedData.book || "";


document.getElementById(
    "workspaceModal"
).style.display = "block";

updateWorkspaceStats();
updateResourcePreview();
}

function closeWorkspace() {

document.getElementById(
    "workspaceModal"
).style.display = "none";

}

function autoSaveWorkspace() {

if (!currentSubject) return;

const workspaceData = {

    notes:
        document.getElementById(
            "workspaceNotes"
        ).value,

    youtube:
        document.getElementById(
            "workspaceYoutube"
        ).value,

    pdf:
        document.getElementById(
            "workspacePdf"
        ).value,

    book:
        document.getElementById(
            "workspaceBook"
        ).value

};

localStorage.setItem(
    `workspace_${currentSubject}`,
    JSON.stringify(workspaceData)
);

updateWorkspaceStats();
updateResourcePreview();

}

function saveWorkspace() {

autoSaveWorkspace();

localStorage.setItem(
    "lastOpenedWorkspace",
    currentSubject
);

alert(
    `✅ ${currentSubject} Workspace Saved!`
);

closeWorkspace();
updateResourcePreview();
}

function clearWorkspace() {

if (
    !confirm(
        `Delete all data for ${currentSubject}?`
    )
) {
    return;
}

localStorage.removeItem(
    `workspace_${currentSubject}`
);

document.getElementById(
    "workspaceNotes"
).value = "";

document.getElementById(
    "workspaceYoutube"
).value = "";

document.getElementById(
    "workspacePdf"
).value = "";

document.getElementById(
    "workspaceBook"
).value = "";

updateWorkspaceStats();
updateResourcePreview();
}

function updateWorkspaceStats() {

const notes =
    document.getElementById(
        "workspaceNotes"
    ).value;

let resources = 0;

if (
    document.getElementById(
        "workspaceYoutube"
    ).value
) resources++;

if (
    document.getElementById(
        "workspacePdf"
    ).value
) resources++;

if (
    document.getElementById(
        "workspaceBook"
    ).value
) resources++;

document.getElementById(
    "notesCount"
).innerHTML =
    notes.length;

document.getElementById(
    "resourceCount"
).innerHTML =
    resources;

}

document.addEventListener(
"DOMContentLoaded",
() => {

    [
        "workspaceNotes",
        "workspaceYoutube",
        "workspacePdf",
        "workspaceBook"
    ].forEach((id) => {

        const element =
            document.getElementById(id);

        if (element) {

            element.addEventListener(
                "input",
                autoSaveWorkspace
            );

        }

    });

}

);
function updateResourcePreview() {

    const youtube =
        document.getElementById(
            "workspaceYoutube"
        ).value;

    const pdf =
        document.getElementById(
            "workspacePdf"
        ).value;

    const book =
        document.getElementById(
            "workspaceBook"
        ).value;

    document.getElementById(
        "resourcePreview"
    ).innerHTML = `

        ${
            youtube
            ?
            `
            <a
                href="${youtube}"
                target="_blank"
                class="resource-card">
                🎥 YouTube Resource
            </a>
            `
            : ""
        }

        ${
            pdf
            ?
            `
            <a
                href="${pdf}"
                target="_blank"
                class="resource-card">
                📄 PDF Resource
            </a>
            `
            : ""
        }

        ${
            book
            ?
            `
            <div class="resource-card">
                📚 ${book}
            </div>
            `
            : ""
        }

    `;
}
const themeBtn = document.getElementById("themeToggle");

themeBtn.addEventListener("click", () => {

    document.body.classList.toggle("dark-mode");

    const isDark =
        document.body.classList.contains("dark-mode");

    localStorage.setItem("theme", isDark);

    themeBtn.innerHTML =
        isDark
            ? "☀️ Light Mode"
            : "🌙 Dark Mode";
});
window.addEventListener("DOMContentLoaded", () => {

    const themeBtn =
        document.getElementById("themeToggle");

    const isDark =
        localStorage.getItem("theme") === "true";

    if (isDark) {
        document.body.classList.add("dark-mode");
        themeBtn.innerHTML = "☀️ Light Mode";
    } else {
        document.body.classList.remove("dark-mode");
        themeBtn.innerHTML = "🌙 Dark Mode";
    }

});
let subjectCount = 1;

document.getElementById("addSubjectBtn")
    .addEventListener("click", () => {

        subjectCount++;

        const container =
            document.getElementById(
                "subjectsContainer"
            );

        container.insertAdjacentHTML(
            "beforeend",
            `
            <h3 class="subject-title">
                📘 Subject ${subjectCount}
            </h3>

            <div class="subject-box">

                <label>Subject Name</label>
                <input
                    id="subject${subjectCount}"
                    type="text">

                <label>Exam Date</label>
                <input
                    id="date${subjectCount}"
                    type="date">

                <label>Priority</label>
                <select id="priority${subjectCount}">
                    <option>High</option>
                    <option>Medium</option>
                    <option>Low</option>
                </select>

                <label>Preparation Level</label>
                <select id="prep${subjectCount}">
                    <option>Poor</option>
                    <option>Average</option>
                    <option>Good</option>
                </select>

            </div>
            `
        );
    });