async function generatePlan() {

    const exam =
        document.getElementById("exam").value;

    const hours =
        parseInt(
            document.getElementById("hours").value
        );

    const subjects = [

        {
            name:
                document.getElementById("subject1").value,

            exam_date:
                document.getElementById("date1").value,

            priority:
                document.getElementById("priority1").value,

            preparation:
                document.getElementById("prep1").value
        },

        {
            name:
                document.getElementById("subject2").value,

            exam_date:
                document.getElementById("date2").value,

            priority:
                document.getElementById("priority2").value,

            preparation:
                document.getElementById("prep2").value
        },

        {
            name:
                document.getElementById("subject3").value,

            exam_date:
                document.getElementById("date3").value,

            priority:
                document.getElementById("priority3").value,

            preparation:
                document.getElementById("prep3").value
        }

    ];

    // Validation

    if (!exam || !hours) {

        alert(
            "Please fill Exam Name and Hours Per Day."
        );

        return;
    }

    if (
        !subjects[0].name ||
        !subjects[1].name ||
        !subjects[2].name
    ) {

        alert(
            "Please enter all subject names."
        );

        return;
    }

    console.log({
        exam,
        subjects,
        hours_per_day: hours
    });

    try {

        // Loading Spinner

        document.getElementById("result")
            .innerHTML = `
            <div class="loading-card">
                <div class="spinner"></div>
                <p>Generating Study Plan...</p>
            </div>
        `;

        const response = await fetch(
            "http://127.0.0.1:8000/generate-plan",
            {
                method: "POST",

                headers: {
                    "Content-Type":
                        "application/json"
                },

                body: JSON.stringify({
                    exam: exam,
                    subjects: subjects,
                    hours_per_day: hours
                })
            }
        );

        if (!response.ok) {

            throw new Error(
                `Server Error: ${response.status}`
            );
        }

        const data =
            await response.json();

        let html = `

            <h2>
                📚 Personalized Study Plan
            </h2>

            <div class="progress-container">

                <div class="progress-text">
                    📈 Progress: 0% Completed
                </div>

                <div class="progress-bar">

                    <div
                        class="progress-fill"
                        id="progressFill">
                    </div>

                </div>

            </div>

        `;

        // Day-wise Schedule

        data.study_plan.forEach((day) => {

            html += `

                <div class="day-card">

                    <h3 class="day-title">
                        📅 ${day.date}
                    </h3>

            `;

            day.tasks.forEach((task) => {

                html += `

                    <div class="plan-card">

                        <div class="plan-left">

                            <input
                                type="checkbox"
                                class="task-checkbox">

                            <span class="task-text">
                                ${task}
                            </span>

                        </div>

                        <div class="task-badge">
                            Study
                        </div>

                    </div>

                `;

            });

            html += `

                </div>

            `;

        });

        html += `

            <div class="quote">

                "Success is the sum of small efforts repeated every day."

            </div>

            <div class="footer">

                🚀 Generated by StudySprint AI

            </div>

        `;

        document.getElementById("result")
            .innerHTML = html;

        updateProgress();

    } catch (error) {

        console.error(error);

        document.getElementById("result")
            .innerHTML = `

            <div class="plan-card">

                ❌ ${error.message}

            </div>

        `;
    }

}

function updateProgress() {

    const checkboxes =
        document.querySelectorAll(
            ".task-checkbox"
        );

    checkboxes.forEach((checkbox) => {

        checkbox.addEventListener(
            "change",
            () => {

                const badge =
                    checkbox
                        .closest(".plan-card")
                        .querySelector(
                            ".task-badge"
                        );

                if (
                    checkbox.checked
                ) {

                    badge.innerHTML =
                        "Completed";

                    badge.classList.add(
                        "completed-badge"
                    );

                } else {

                    badge.innerHTML =
                        "Study";

                    badge.classList.remove(
                        "completed-badge"
                    );

                }

                const total =
                    document.querySelectorAll(
                        ".task-checkbox"
                    ).length;

                const completed =
                    document.querySelectorAll(
                        ".task-checkbox:checked"
                    ).length;

                const percent =
                    Math.round(
                        (
                            completed /
                            total
                        ) * 100
                    );

                document.querySelector(
                    ".progress-text"
                ).innerHTML =
                    `📈 Progress: ${percent}% Completed`;

                document.getElementById(
                    "progressFill"
                ).style.width =
                    percent + "%";

            }
        );

    });

}