stages:
  - quality

quality-checks:
  stage: quality

  before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install ruff mypy bandit vulture

  script:
    - ruff check .
    - ruff format --check .
    - mypy backend
    - bandit -r backend
    - vulture backend --min-confidence 80

  only:
    - main
