from google.adk.agents import LlmAgent

def generate_study_plan_tool(
    exam: str,
    subjects: str,
    hours_per_day: float
):
    return f"""
StudySprint Generated Plan

Exam: {exam}
Subjects: {subjects}
Hours Per Day: {hours_per_day}

A detailed study plan will be generated by StudySprint AI.
"""

study_agent = LlmAgent(
    name="StudySprintAgent",
    model="gemini-2.5-flash",
    instruction="""
You are StudySprint AI.

Your responsibilities:
- Create study plans
- Suggest revision schedules
- Give personalized study advice
- Help students prepare efficiently

Use tools whenever needed.
""",
    tools=[generate_study_plan_tool]
)